COR FIX Reviews fixes and enhancements
YotpoLtd/magento2-module-reviews pull request #62
Opened 2022-03-07 16:23 UTC by DanielxC

2022-03-07 16:41 UTC, DanielxC commented on Block/Adminhtml/Report/Reviews.php
> +                $dateStart->modify('-2 years');
All of this changes were tested and working as expected:
![image](https://user-images.githubusercontent.com/10895971/157077985-3ff6d833-b335-43ab-a75f-a8b57cf02997.png)

2022-03-17 07:54 UTC, EranAvidor commented on Controller/Adminhtml/External/AbstractReviews.php
> +                if ($this->yotpoConfig->isActivated($storeId, $scope)) {
I think it should stay scope on this case and follow Magento terminology

2022-03-17 07:56 UTC, EranAvidor commented on Model/Sync/Main.php
> +    public function request($method, $url, array $data = []): DataObject
I’m actually not sure :)
@gingi?

2022-03-17 07:58 UTC, EranAvidor commented on Block/Adminhtml/Report/Reviews.php
>              case '24h':
Let’s separate these logical changes to a stand alone pr.
The comment below is great!

2022-03-17 07:59 UTC, EranAvidor commented on Block/Adminhtml/Report/Reviews.php
> +            default:
Default before custom? Does that make sense?
If there are no cases like that (default) let’s add this commit to the other PR with the time calculation fixes.

2022-03-17 08:00 UTC, EranAvidor commented on .gitignore
> +
Last line should be removed.

2022-03-17 08:00 UTC, EranAvidor requested changes
Added comments

2022-03-31 14:25 UTC, DanielxC commented on Controller/Adminhtml/External/AbstractReviews.php
> +                if ($this->yotpoConfig->isActivated($storeId, $scope)) {
We could, I changed it because there's already scopeId variable defined in this method: [Line](https://github.com/YotpoLtd/magento2-module-reviews/pull/62/commits/60a0905be85c22db5c65d19bf224150de55b44ce#diff-7810922eda3cb1033e03d4e7f5b7ed124efa108a2d05f1805c78132752e3a730R43)
WDYT?

2022-03-31 14:25 UTC, DanielxC commented on Controller/Adminhtml/External/AbstractReviews.php
> +                if ($this->yotpoConfig->isActivated($storeId, $scope)) {
We could, I changed it because there's already scopeId variable defined in this method: [Line](https://github.com/YotpoLtd/magento2-module-reviews/pull/62/commits/60a0905be85c22db5c65d19bf224150de55b44ce#diff-7810922eda3cb1033e03d4e7f5b7ed124efa108a2d05f1805c78132752e3a730R43)
should we still change it back?

2022-03-31 14:26 UTC, DanielxC commented on Model/Sync/Main.php
> +    public function request($method, $url, array $data = []): DataObject
I dropped this commit, as `sync` is the convention in the extension, so I think we should keep it named `sync`.

2022-03-31 14:28 UTC, DanielxC commented on Block/Adminhtml/Report/Reviews.php
> +            default:
changed it to the end of the switch case in the other PR.

2022-03-31 14:40 UTC, DanielxC commented on Block/Adminhtml/Report/Reviews.php
> +            default:
I think adding default even if there is no cases, are a good practice - added it in the bottom in the other PR.

2022-03-31 14:40 UTC, DanielxC commented on Block/Adminhtml/Report/Reviews.php
> +            default:
added it in the bottom in the other PR.

2022-03-31 14:46 UTC, DanielxC commented on Block/Adminhtml/Report/Reviews.php
>              case '24h':
dropped these changes and created another PR for it:
https://github.com/YotpoLtd/magento2-module-reviews/pull/67

2024-07-31 12:31 UTC, closed without merging