SPK-246 v3 widgets
YotpoLtd/magento2-module-reviews pull request #83
Opened 2023-04-27 15:20 UTC by ashotnazaryan-yotpo

2023-05-08 21:27 UTC, LiorGingi requested changes

2023-05-08 21:27 UTC, LiorGingi commented on Block/Yotpo.php
> +        return $instanceId !== false && $this->yotpoConfig->isV3Enabled();
```
$instanceId !== false
````

Can $instanceId be explicitly false here?

2023-05-08 21:27 UTC, LiorGingi commented on Block/Yotpo.php
> +        return $instanceId !== false && $this->yotpoConfig->isV3Enabled();
```
return $instanceId !== false && $this->yotpoConfig->isV3Enabled();
```

This is a duplicated line, please extract it into a separate method.

2023-05-08 21:27 UTC, LiorGingi commented on Model/Config.php
> +        'widget_v3_instance_ids_last_sync_time' => ['path' => 'yotpo/settings/widget_v3_instance_ids_last_sync_time'],
Why the new configs are under the `yotpo/settings` path?
It should be under `yotpo/reviews` in this case.

The `yotpo/settings` is reserved for migrating from older versions of the plugin.

2023-05-08 21:27 UTC, LiorGingi commented on view/frontend/templates/widget_div.phtml
> +        data-yotpo-instance-id="<?= $block->getReviewsInstanceId() ?>"
What happens if we don't have the instance ID for any reason? Shouldn't we have a fallback to the older widget until issue is resolved?

2023-05-08 21:27 UTC, LiorGingi commented on view/frontend/templates/widget_script.phtml
> +<?php if ($block->isV3ReviewsWidget() || $block->isV3StarRatingWidget()): ?>
Can someone have V3 widgets disabled but have the V3 star rating enabled?

2023-05-08 21:27 UTC, LiorGingi commented on view/frontend/layout/default.xml
> +</page>
Missing EOL here.

2023-05-08 21:27 UTC, LiorGingi commented on etc/adminhtml/system.xml
> +                            Use this button to sync new or updated V3 widgets.
Was this reviewed by a PM?

2023-05-08 21:27 UTC, LiorGingi commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +            $this->yotpoConfig->saveConfig('sync_widget_v3_instance_ids_data', (string)$serializedData);
I do understand that the idea behind saving a JSON into the DB seems to be more efficient, but I'm personally not a fan.
I wonder why not saving the instance ID of each widget individually as a config?

2023-05-09 06:15 UTC, ashotnazaryan-yotpo commented on view/frontend/templates/widget_div.phtml
> +        data-yotpo-instance-id="<?= $block->getReviewsInstanceId() ?>"
If we don't have the instance ID, this condition on parent element won't pass
`if ($block->isV3ReviewsWidget())`
which checks whether the instanceId is there and the checkbox is checked
```
public function isV3ReviewsWidget()
    {
        $instanceId = $this->getReviewsInstanceId();

        return $instanceId !== false && $this->yotpoConfig->isV3Enabled();
    }
```
and the next condition will be checked
`elseif ($block->isRenderWidget())`

2023-05-09 06:17 UTC, ashotnazaryan-yotpo commented on view/frontend/templates/widget_script.phtml
> +<?php if ($block->isV3ReviewsWidget() || $block->isV3StarRatingWidget()): ?>
I used the same approach as in case of Shopify
https://github.com/YotpoLtd/ugc-shopify-app-extensions/blob/master/extensions/theme-app-extension/blocks/settings.liquid#LL1
here we load the script if there is either V3 star ratings or V3 main widget

2023-05-09 06:18 UTC, ashotnazaryan-yotpo commented on etc/adminhtml/system.xml
> +                            Use this button to sync new or updated V3 widgets.
Still waiting for the response from the PM. This text is likely to be changed. That's why the PR is in draft mode.

2023-05-09 09:57 UTC, lukaszpluto commented on Block/Yotpo.php
> +        return $instanceId !== false && $this->yotpoConfig->isV3Enabled();
yes, e.g. https://github.com/YotpoLtd/magento2-module-reviews/pull/83/files#diff-9d8f8bb39dfd46426a24d8fd10c888e246a3a501d2684a7a3af5da46b8c8af58R281 and a few line below

2023-05-09 11:15 UTC, lukaszpluto commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +            $this->yotpoConfig->saveConfig('sync_widget_v3_instance_ids_data', (string)$serializedData);
it simplifies things when new widget types will be added to API response. Storing each widget separately should require checking if such type is supported and then save / get config by the name

2023-07-05 22:12 UTC, LiorGingi requested changes

2023-07-05 22:12 UTC, LiorGingi commented on Model/Config/Backend/FormatDate.php
> +class FormatDate extends \Yotpo\Core\Model\Config\Backend\FormatDate
Why is this needed?

2023-07-05 22:12 UTC, LiorGingi commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +    public function syncWidgetV3InstanceIds()
Why is the method called `sync` if it's not syncing? it's `getWidgetV3InstanceIds`.

2023-07-07 07:30 UTC, lukaszpluto commented on view/frontend/templates/widget_script.phtml
> +<?php if ($block->isV3ReviewsWidget() || $block->isV3StarRatingWidget()): ?>
@ashotnazaryan-yotpo replied on the meeting that similar approach is implemented in Shopify extension

2023-07-07 07:30 UTC, lukaszpluto commented on Block/Adminhtml/System/Config/Form/Field/RemoveScopes.php
> +namespace Yotpo\Reviews\Block\Adminhtml\System\Config\Form\Field;
removed

2023-07-07 07:30 UTC, lukaszpluto commented on Model/Config.php
> +            return strlen($v3InstanceId) > 0 ? $v3InstanceId : false;
changed

2023-07-07 07:31 UTC, lukaszpluto commented on Model/Config/Backend/FormatDate.php
> +class FormatDate extends \Yotpo\Core\Model\Config\Backend\FormatDate
removed

2023-07-12 05:59 UTC, LiorGingi commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +    public function syncWidgetV3InstanceIds()
I don't see it was changed.

2023-07-12 06:37 UTC, lukaszpluto commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +    public function syncWidgetV3InstanceIds()
sorry, wasn't in commit by mistake

2023-07-13 11:16 UTC, LiorGingi approved these changes

2023-07-13 13:36 UTC, merged