fix(bottomline.phtml): fix bottomline qna
YotpoLtd/magento2-module-reviews pull request #90
Opened 2023-07-25 15:04 UTC by ashotnazaryan-yotpo

2023-07-25 19:31 UTC, LiorGingi requested changes

2023-07-25 19:31 UTC, LiorGingi commented on view/frontend/templates/bottomline.phtml
> +    <?php if ($block->isRenderBottomlineQna()): ?>
As discussed, the bottomline Q&A widget should appear if the V3 widgets is disabled.
Please add this condition.

2023-07-26 06:07 UTC, ashotnazaryan-yotpo commented on view/frontend/templates/bottomline.phtml
> +    <?php if ($block->isRenderBottomlineQna()): ?>
if v3 widgets are disabled from the admin settings or if v3 star ratings (if ($block->isV3StarRatingWidget())) is not there ?

2023-07-26 14:37 UTC, LiorGingi approved these changes

2023-07-26 14:42 UTC, merged