feat(wiget_v3): not enable v3 when instances are empty
YotpoLtd/magento2-module-reviews pull request #91
Opened 2023-08-21 14:16 UTC by lukaszpluto

2023-08-31 04:44 UTC, sharp80 commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +                );
why not just do return; from this line instead of adding another else? is this some convention to add more and more if/elses ?

2023-08-31 04:46 UTC, sharp80 commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +                foreach ($responseData['widget_instances'] as $widgetInstance) {
i don't understand - you added a fix for missing instances above -> why did you need to write this code? isn't the json encode is good enough?
` $serializedData = json_encode($widgetV3InstanceIds);`

2023-09-03 12:27 UTC, LiorGingi requested changes

2023-09-03 12:27 UTC, LiorGingi commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +                );
I agree with @sharp80, early returns are a better practice.

2023-09-04 06:59 UTC, lukaszpluto commented on Model/Sync/WidgetV3InstanceIds/Processor.php
> +                foreach ($responseData['widget_instances'] as $widgetInstance) {
There are some not needed fields in the response and I need only `widget_instance_id`

2023-09-04 13:28 UTC, LiorGingi approved these changes

2023-09-05 12:14 UTC, merged